import streamlit as st
import pandas as pd
import plotly.express as px
import datetime
from database import supabase, check_auth, apply_custom_design
from fpdf import FPDF

apply_custom_design()

st.set_page_config(page_title="Academic Transcript", layout="wide")

if "Home" not in st.session_state:
    check_auth()

username = st.session_state.username

st.header("📜 Unofficial Academic Transcript & CGPA")
st.info(f"Welcome back, **{username}**! Your history is retrieved automatically.")

# --- PDF GENERATOR FUNCTION ---
def create_pdf(df, full_name, cgpa):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 16)
    pdf.cell(200, 10, txt="BEZUB ACADEMIC SYSTEMS", ln=True, align='C')
    pdf.set_font("Arial", "B", 14)
    pdf.cell(200, 10, txt=f"Unofficial Transcript for: {full_name.upper()}", ln=True, align='C')
    pdf.set_font("Arial", "", 12)
    pdf.cell(200, 10, txt=f"Overall CGPA: {round(cgpa, 3)}", ln=True, align='C')
    pdf.cell(200, 10, txt=f"Issued on: {datetime.date.today()}", ln=True, align='C')
    pdf.ln(10)
    pdf.set_fill_color(243, 234, 253)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(60, 10, "Date Recorded", 1, 0, 'C', True)
    pdf.cell(60, 10, "Semester GPA", 1, 0, 'C', True)
    pdf.cell(60, 10, "Credits (ECTS)", 1, 1, 'C', True)
    pdf.set_font("Arial", "", 12)
    for index, row in df.iterrows():
        pdf.cell(60, 10, str(row['Date Recorded']), 1, 0, 'C')
        pdf.cell(60, 10, str(row['Semester GPA']), 1, 0, 'C')
        pdf.cell(60, 10, str(row['Credits (ECTS)']), 1, 1, 'C')
    pdf.ln(20)
    pdf.set_font("Arial", "I", 8)
    pdf.multi_cell(0, 5, txt="DISCLAIMER: This document is an unofficial record generated by Bezub Academic Systems.")
    return bytes(pdf.output())

# --- DATA RETRIEVAL ---
with st.spinner("Accessing cloud records..."):
    response = supabase.table("gpa_records").select("*").eq("username", username).execute()

    if not response.data:
        st.warning(f"Hello {username}, we couldn't find any records yet.")
        st.write("Go to the **GPA Calculator** page to calculate and save your first semester!")
    else:
        df = pd.DataFrame(response.data)
        df['created_at_dt'] = pd.to_datetime(df['created_at']) # Keep full timestamp for precise deletion
        df['Date Recorded'] = df['created_at_dt'].dt.date

        total_quality_points = (df['gpa'] * df['total_ects']).sum()
        grand_total_ects = df['total_ects'].sum()
        cgpa = round(total_quality_points / grand_total_ects, 2) if grand_total_ects > 0 else 0

        st.divider()
        col1, col2, col3 = st.columns(3)
        col1.metric(label="Cumulative GPA", value=f"{cgpa:.3f}")
        col2.metric(label="Total Credits Earned", value=int(grand_total_ects))
        col3.metric(label="Semesters Recorded", value=len(df))

        display_df = df[['Date Recorded', 'gpa', 'total_ects']].sort_values(by='Date Recorded', ascending=False)
        display_df.columns = ['Date Recorded', 'Semester GPA', 'Credits (ECTS)']
        st.dataframe(display_df, use_container_width=True, hide_index=True)

        # --- DELETE LOGIC SECTION ---
        st.divider()
        st.subheader("Manage Records")
        with st.expander("Remove an Incorrect Entry"):
            # We use the full original list to ensure we can map back to the ID or exact timestamp
            to_delete_date = st.selectbox("Select Record Date to Delete:", df['created_at'].tolist())
            if st.button("Delete Permanently", type="primary"):
                supabase.table("gpa_records").delete().eq("username", username).eq("created_at", to_delete_date).execute()
                st.success("Record removed!")
                st.rerun()

        # Progress Chart
        df_sorted = df.sort_values(by='created_at')
        df_sorted['Total_Points'] = df_sorted['gpa'] * df_sorted['total_ects']
        df_sorted['Cumulative_Points'] = df_sorted['Total_Points'].cumsum()
        df_sorted['Cumulative_ECTS'] = df_sorted['total_ects'].cumsum()
        df_sorted['Progressive_CGPA'] = (df_sorted['Cumulative_Points'] / df_sorted['Cumulative_ECTS']).round(3)

        fig = px.line(df_sorted, x='Date Recorded', y=['gpa', 'Progressive_CGPA'],
                      labels={'value': 'GPA Score', 'Date Recorded': 'Date', 'variable': 'Type'},
                      title="GPA vs. Cumulative Trend",
                      markers=True,
                      color_discrete_sequence=["#D1B3FF", "#4A148C"])

        fig.update_yaxes(range=[0, 4])

        st.plotly_chart(fig, use_container_width=True)

        st.divider()
        st.subheader(" Target CGPA Roadmap")
        next_credits = st.number_input("Expected Credits for Next Semester:", 1, 40, 30)
        curr_points = (df['gpa'] * df['total_ects']).sum()
        curr_ects = df['total_ects'].sum()
        targets = [3.5, 3.6, 3.7, 3.8, 3.9, 4.0]
        goal_data = []
        for t in targets:
            if t <= cgpa and t < 4.0: continue
            req = ((t * (curr_ects + next_credits)) - curr_points) / next_credits
            goal_data.append({"Target CGPA": t, "Required Next GPA": round(req, 2), "Status": "✅ Possible" if req <= 4.0 else "⚠️ Hard (>4.0)"})
        if goal_data: st.table(pd.DataFrame(goal_data))

        st.divider()
        st.subheader(" Export Unofficial Document")
        full_name_input = st.text_input("Full Name:", placeholder="e.g. Johnathan Doe")
        if full_name_input:
            try:
                pdf_bytes = create_pdf(display_df, full_name_input, cgpa)
                st.download_button(label="Download Unofficial PDF Transcript", data=pdf_bytes, file_name=f"{full_name_input.replace(' ', '_')}_Transcript.pdf", mime="application/pdf")
            except Exception as e: st.error(f"Error: {e}")

st.markdown(
    "<p style='text-align: center; color: #4A148C; font-size: 12px; margin-top: 50px; opacity: 0.6;'>© 2026 Bezub Academic Systems.</p>",
    unsafe_allow_html=True)


